### PR TITLE
 new: array-bracket-newline that handles objectsInArrays

### PR DESCRIPTION
**Pull request by andreineculau**

### CODE REVIEW

**Comment by andreineculau** [comment]
more tests coming

**Comment by IanSavchenko** [comment]
> naming is taken from https://eslint.org/docs/rules/array-bracket-spacing . I don't have a preference, come up with smth and I change it.

Leaving the hardest problem for me? 😆 In the case of that rule, `objectsInArrays` acts as an exception to whatever main param is set (always or never). Here I would say it's `allowObjectCurly` (logic has to be reversed too). 

And I also can't understand (too tired to think, tbh) if your rule is handling cases when you have objects and non-objects mixed and what will happen with the array bracket that is not next to an object.

A case like: 

```
let arr = [{
    a: 'b'
  },
  'string'
];
```

**Comment by andreineculau** [comment]
changed the logic a bit to focus only on the last item, handling cases where last item is an options blob like in a eslint-rule pattern `['error', {option1: true}]`

to be all strict, i should check that all but last item are objects, or anything but objects, but that made the naming even harder.

**Comment by IanSavchenko** [comment]
But why did you abandon first array item which can be an object? We don't care what is inside the array, but if we have the discussed flag enabled (`objectsInArrays` or `allowObjectCurly` or whatever we call it in the end) then if
1) we have first array item as object, it should preserve curly on the same line as opening array bracket
2) we have last array item as object, it should preserve curly on the same line as closing array bracket

And these conditions a) work independently, b) don't care about items in the middle of the array, whatever they are, objects or not..

**Comment by andreineculau** [comment]
updating the naming to `allowObjectCurly` and it also handles the first array item now

**Comment by andreineculau** [comment]
Sorry, not my intention 😞 
We run with this and if life throws lemons at us we make lemonade 👍

**Pull request merged**
