### PR TITLE
F/anu object property newline

### PR DESCRIPTION
**Pull request by andreineculau**
realized we are missing actually a rule

EDIT: a complement to the custom object-curly-newline

### CODE REVIEW

**Comment by andreineculau** [comment]
without this, I got

```js
export let makeLocalHandler = function({lambda: {mainFun, awsFunctionName}}) {
```

"fixed" into

```js
export let makeLocalHandler = function({
  lambda: {
    mainFun, awsFunctionName
  }
}) {
```

**Comment by andreineculau** [comment]
more commits. we also didn't handle `function({a} = {})` cases for only-param...

**Comment by andreineculau** [comment]
examples of changes when jumping from 0.3 to future 0.5 (this branch HEAD): https://github.com/tobiipro/aws-util-firecloud/compare/f/new-eslint-config-firecloud

**Comment by IanSavchenko** [comment]
LGTM, though arrays spanned across several lines look weird. I would allow up to 2 elements in array to be on the same line. Or maybe at least 1.

**Comment by andreineculau** [comment]
> LGTM, though arrays spanned across several lines look weird.

then we're not consistent imo. why allow 1 or 2 array elements, but not 1 or 2 object properties?

I'm merging since the comment it's not tied to this particular PR (targeting objects), and we can see later how we want to address this, ok?

**Pull request merged**
